Integrated Starting Point, VIP and VIP+ HTB VPNs logic to htb-spawn

diff --git a/x86_64/packages/htb-tools/usr/local/bin/htb-spawn b/x86_64/packages/htb-tools/usr/local/bin/htb-spawn
--- a/x86_64/packages/htb-tools/usr/local/bin/htb-spawn
+++ b/x86_64/packages/htb-tools/usr/local/bin/htb-spawn
@@ -84,38 +84,39 @@ VPNArray+=("USVIP+1")
 ## SG
 VPNArray+=("SGVIP+1")
 
-machine_json_file="$HOME/.machine.json"
+# Starting Point VPN
+VPNArrayStartingPoint=("EUSPFree1" "EUSPVIP1" "USSPFree1" "USSPVIP1")
 
-if nmcli c show --active | grep -q tun ; then
-  echo "VPN Server already running."
-else  
-  while [[ ! ${VPNArray[*]} =~ (^|[[:space:]])$vpn_server($|[[:space:]]) ]] #Use of ':space:' for Exact match in the array
-  do
-     echo "VPN Server not running. Type one of the following VPN servers:"
-     echo -e "\e[36mStarting Point Free VPN: EUSPFree1 USSPFree1\e[0m"
-     echo -e "\e[36mStarting Point VIP VPN: EUSPVIP1 USSPVIP1\e[0m"
-     echo -e
-     echo -e "\e[36mMachines Free VPN: EUFree1 EUFree2 EUFree3 USFree1 USFree2 USFree3 AUFree1 SGFree1\e[0m"
-     echo -e "\e[33mMachines VIP VPN: EUVIP1 to EUVIP28 or USVIP1 to USVIP27 or SGVIP1 SGVIP2 AUVIP1\e[0m"
-     echo -e "\e[31mMachines VIP+ VPN: EUVIP+1 EUVIP+2 USVIP+1 SGVIP+1\e[0m"
-     echo -n "VPN Server:"
-     read vpn_server
-     htb-vpn $vpn_server
-  done
-fi
+machine_json_file="$HOME/.machine.json"
 
 { # try # Test if the API key is valid
 
     curl -s --location --request GET "https://www.hackthebox.com/api/v4/machine/profile/$machine_name" -H "Authorization: Bearer $appkey" | jq > $machine_json_file
 
 } || { # catch
-    echo "\e[31mError. Maybe your API key is incorrect or expired. Renew your API key by running htb-update.\e[0m"
+    echo -e "\e[31mError. Maybe your API key is incorrect or expired. Renew your API key by running htb-update.\e[0m"
     rm -rf $machine_json_file
     exit 1
 }
 
 if cat $machine_json_file | grep -q "Starting Point Machine"; then
     if curl -s --location --request POST https://www.hackthebox.com/api/v4/vm/spawn --data "{\"machine_id\":$machine_id}" -H "Content-Type: application/json" -H "Authorization: Bearer $appkey" | jq '.message' | grep -q "Machine deployed to lab."; then
+
+        if [ nmcli c show --active | grep -q tun ] && [ curl -s --location --request GET https://www.hackthebox.com/api/v4/connection/status -H "Authorization: Bearer $appkey" | jq '.[0].type' | grep -q "Starting Point" ]; then
+             echo "Starting Point VPN Server already running."
+        else
+          while [[ ! ${VPNArrayStartingPoint[*]} =~ (^|[[:space:]])$vpn_server($|[[:space:]]) ]] # Until the VPN input is not contained in the VPNArray variable, loop. Use of ':space:' for Exact match in the array
+          do
+             echo -e 'Please, provide one VPN server you prefer to connect:'
+             echo -e "\e[36m┌────────────────────────────────────────────────────┐\e[0m"
+             echo -e "\e[36m| Starting Point Free VPN : EUSPFree1 USSPFree1      |\e[0m"
+             echo -e "\e[33m| Starting Point VIP VPN  : EUSPVIP1  USSPVIP1       |\e[0m"
+             echo -e "\e[31m└────────────────────────────────────────────────────┘\e[0m"
+             echo -ne "VPN Server:"
+             read vpn_server
+             htb-vpn $vpn_server
+          done
+        fi
 
         machine_ip=""
         echo "Waiting for IP address to be assigned to the target machine. It will take around 1 minute..."
@@ -126,16 +127,23 @@ if cat $machine_json_file | grep -q "Starting Point Machine"; then
         done
         machine_points="0"
 
+        printf '%b\n' "$(base64 -d <<<"H4sIAAAAAAAAA+1buw6DMAzc+xVZWlUoSlCZqn5K+wv8/9oHUgkQIEBCDtueqlOHi+/imICVihunsL+9yqp6lo/7rb42P+t1iB1CcVjqWAzxkW3ZCtJEkH0QvU5GtGWkQ8wnyG5tu0h5g0Y/XhqME2jsEno7RHmyxVkbT9Bdbl9sV2g0rnsiymeDf9At/cZjBTSSCXfDbHx9wSghXSsQOQTnVW6jQCO/RUdaMkbLTYgP0EiLnagjU7Yk239wtbXl1FQMEd00Vp1GC41jXiT3CZRva2g5gJ2bKNbbomhysOtlTHbjE3oKWYcwb3ecM5Gf8dmXfnyk17gx9aih/JJgiBSeh1K+ygNUqZHbAtFENBFNRBPRRDQRTUSTuJoc8jLKl0VhFN8bZzR66RAs8Tp2UnQvz6zuGu4XZJ/BC0R/oSUpHeJ+ET/4GJbR9bxCEL4hccjuY7v7vA48bDe2DjG5t5yhO9hlLx5rjc/8kD1wBVncoox5ZHpMUhyUsYxNRMAILtp6otXA0RG4BcnZ4O3J+cuWwxtaDodVdT0AAA==" | gunzip)" #User printf for colored output
+        echo
+
         change_shell $machine_name $machine_ip $htb_user $machine_points
 
         echo -e "Remember to activate the VPN for HTB Starting Point Machines."
         echo -e "\e[33mFor submitting the answers of the task questions, visit Hack The Box website: https://app.hackthebox.com/starting-point\e[0m"
         echo -e "\e[32mPlaying $machine_name. Good luck!\e[0m"
         echo
-
+    elif curl -s --location --request POST https://www.hackthebox.com/api/v4/vm/spawn --data "{\"machine_id\":$machine_id}" -H "Content-Type: application/json" -H "Authorization: Bearer $appkey" | jq '.message' | grep -q "Machine is VIP only."; then
+        echo "Machine is VIP only."
+        echo
+        exit 1
     elif curl -s --location --request POST https://www.hackthebox.com/api/v4/vm/spawn --data "{\"machine_id\":$machine_id}" -H "Content-Type: application/json" -H "Authorization: Bearer $appkey" | jq '.message' | grep -q "You must stop your active machine before spawning another one."; then
         echo "You must stop your active machine before spawning another one."
         echo
+        exit 1
     fi
 else
 
@@ -147,18 +155,35 @@ else
 
     rm -rf $machine_json_file
 
-    if [ $machine_userflag != "null" ]; then
-      echo "Hey! You have already found the User Flag! Nice one!"
-    fi
-
-    if [ $machine_rootflag != "null" ]; then
-      echo "Hey! You have already found the Root Flag! Keep it up!"
-    fi
-
-    printf '%b\n' "$(base64 -d <<<"H4sIAAAAAAAAA+1buw6DMAzc+xVZWlUoSlCZqn5K+wv8/9oHUgkQIEBCDtueqlOHi+/imICVihunsL+9yqp6lo/7rb42P+t1iB1CcVjqWAzxkW3ZCtJEkH0QvU5GtGWkQ8wnyG5tu0h5g0Y/XhqME2jsEno7RHmyxVkbT9Bdbl9sV2g0rnsiymeDf9At/cZjBTSSCXfDbHx9wSghXSsQOQTnVW6jQCO/RUdaMkbLTYgP0EiLnagjU7Yk239wtbXl1FQMEd00Vp1GC41jXiT3CZRva2g5gJ2bKNbbomhysOtlTHbjE3oKWYcwb3ecM5Gf8dmXfnyk17gx9aih/JJgiBSeh1K+ygNUqZHbAtFENBFNRBPRRDQRTUSTuJoc8jLKl0VhFN8bZzR66RAs8Tp2UnQvz6zuGu4XZJ/BC0R/oSUpHeJ+ET/4GJbR9bxCEL4hccjuY7v7vA48bDe2DjG5t5yhO9hlLx5rjc/8kD1wBVncoox5ZHpMUhyUsYxNRMAILtp6otXA0RG4BcnZ4O3J+cuWwxtaDodVdT0AAA==" | gunzip)" #User printf for colored output
-    echo
-
     if curl -s --location --request POST "https://www.hackthebox.com/api/v4/machine/play/$machine_id" -H "Authorization: Bearer $appkey" | jq '.message' | grep -q "Playing"; then
+
+        if [ nmcli c show --active | grep -q tun ] && ([ curl -s --location --request GET https://www.hackthebox.com/api/v4/connection/status -H "Authorization: Bearer $appkey" | jq '.[0].type' | grep -q "Free" ] || [ curl -s --location --request GET https://www.hackthebox.com/api/v4/connection/status -H "Authorization: Bearer $appkey" | jq '.[0].type' | grep -q "VIP" ]); then
+             echo "Lab VPN Server already running."
+        else
+          while [[ ! ${VPNArray[*]} =~ (^|[[:space:]])$vpn_server($|[[:space:]]) ]] # Until the VPN input is not contained in the VPNArray variable, loop. Use of ':space:' for Exact match in the array
+          do
+             echo 'Please, provide one VPN server you prefer to connect:'
+             echo -e "\e[36m┌────────────────────────────────────────────────────┐\e[0m"
+             echo -e "\e[36mMachines Free VPN: EUFree1 EUFree2 EUFree3 USFree1 USFree2 USFree3 AUFree1 SGFree1\e[0m"
+             echo -e "\e[36mMachines VIP VPN: EUVIP1 to EUVIP28 or USVIP1 to USVIP27 or SGVIP1 SGVIP2 AUVIP1\e[0m"
+             echo -e "\e[36mMachines VIP+ VPN: EUVIP+1 EUVIP+2 USVIP+1 SGVIP+1\e[0m"
+             echo -e "\e[36m└────────────────────────────────────────────────────┘\e[0m"
+             echo -ne "VPN Server:"
+             read vpn_server
+             htb-vpn $vpn_server
+          done
+        fi
+
+        printf '%b\n' "$(base64 -d <<<"H4sIAAAAAAAAA+1buw6DMAzc+xVZWlUoSlCZqn5K+wv8/9oHUgkQIEBCDtueqlOHi+/imICVihunsL+9yqp6lo/7rb42P+t1iB1CcVjqWAzxkW3ZCtJEkH0QvU5GtGWkQ8wnyG5tu0h5g0Y/XhqME2jsEno7RHmyxVkbT9Bdbl9sV2g0rnsiymeDf9At/cZjBTSSCXfDbHx9wSghXSsQOQTnVW6jQCO/RUdaMkbLTYgP0EiLnagjU7Yk239wtbXl1FQMEd00Vp1GC41jXiT3CZRva2g5gJ2bKNbbomhysOtlTHbjE3oKWYcwb3ecM5Gf8dmXfnyk17gx9aih/JJgiBSeh1K+ygNUqZHbAtFENBFNRBPRRDQRTUSTuJoc8jLKl0VhFN8bZzR66RAs8Tp2UnQvz6zuGu4XZJ/BC0R/oSUpHeJ+ET/4GJbR9bxCEL4hccjuY7v7vA48bDe2DjG5t5yhO9hlLx5rjc/8kD1wBVncoox5ZHpMUhyUsYxNRMAILtp6otXA0RG4BcnZ4O3J+cuWwxtaDodVdT0AAA==" | gunzip)" #User printf for colored output
+        echo
+
+        if [ $machine_userflag != "null" ]; then
+          echo "Hey! You have already found the User Flag! Nice one!"
+        fi
+
+        if [ $machine_rootflag != "null" ]; then
+          echo "Hey! You have already found the Root Flag! Keep it up!"
+        fi
 
         change_shell $machine_name $machine_ip $htb_user $machine_points
 
@@ -168,8 +193,10 @@ else
     elif curl -s --location --request POST "https://www.hackthebox.com/api/v4/machine/play/$machine_id" -H "Authorization: Bearer $appkey" | jq '.message' | grep -q "Machine is VIP only"; then
         echo "Machine is VIP only."
         echo
+        exit 1
     elif curl -s --location --request POST "https://www.hackthebox.com/api/v4/machine/play/$machine_id" -H "Authorization: Bearer $appkey" | jq '.message' | grep -q "Machine is on Release Arena"; then
         echo "Machine is on Release Arena."
         echo
+        exit 1
     fi
 fi
